disabled_rules: # rule identifiers to exclude from running
  - line_length
  - trailing_whitespace
  - identifier_name
  - function_body_length
  - cyclomatic_complexity
  - superfluous_disable_command
  - force_cast
  - type_name
  - function_parameter_count
  - nesting
  - weak_delegate
  #- type_name

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Templates
  - Output

file_length:
  warning: 1000
  error: 2000

type_body_length:
  warning: 500
  error: 1000

nesting:
  warning: 500
  error: 1000
