source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

def shared_pods
   pod 'IQKeyboardManagerSwift', '5.0.7'
   pod 'KeychainAccess', '3.1.0'
   pod 'Kommander', '0.9.3'
   pod 'Reusable', '4.0.0'
   pod 'SnapKit', '4.0.0'
   pod 'Swinject', '2.1.1'
   pod 'PocketNet', '1.3.3'
end

target 'Jinsoku' do
   shared_pods
end
